AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Application.
Parameters:
  SecurityGroupId:
    Type: 'AWS::EC2::SecurityGroup::Id'
  SubNetId1:
    Type: 'AWS::EC2::Subnet::Id'
  SubNetId2:
    Type: 'AWS::EC2::Subnet::Id'
  SubNetId3:
    Type: 'AWS::EC2::Subnet::Id'
  SubNetId4:
    Type: 'AWS::EC2::Subnet::Id'
  SubNetId5:
    Type: 'AWS::EC2::Subnet::Id'
  SubNetId6:
    Type: 'AWS::EC2::Subnet::Id'
  EnvironmentType:
    Description: The environment type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - uat
      - prod
    ConstraintDescription: 'Must be dev, uat or prod'
Mappings:
  EnvironmentVariablesMap:
    Function.Properties.CodeUri.Bucket:
      dev: vanlune-bin-dev
      uat: vanlune-bin-uat
      prod: vanlune-bin-prod
    Function.Properties.Orders.Bucket:
      dev: vanlune-database
      uat: vanlune-database
      prod: vanlune-database
    Stage.ApiGateway:
      dev: Dev
      uat: Uat
      prod: Prod
    DbSecretName: 
      dev: vanlune-db-dev
      uat: vanlune-db-dev
      prod: vanlune-db-dev
Resources:
 # API Functinos
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !FindInMap 
          - EnvironmentVariablesMap
          - Stage.ApiGateway
          - !Ref EnvironmentType
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
  CreateProduct:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: vanlune-orders-create
      Handler: >-
        Orders.Application::Orders.Application.Function::CreateOrders
      Runtime: dotnetcore3.1
      CodeUri:
        Bucket: !FindInMap 
          - EnvironmentVariablesMap
          - Function.Properties.CodeUri.Bucket
          - !Ref EnvironmentType
        Key: Orders.zip
      MemorySize: 256
      Timeout: 900
      Role: !Join ['', ['arn:aws:iam::', !Ref 'AWS::AccountId', ':role/role-lambda-vanlune']]
      Policies:
        - AWSLambdaBasicExecutionRole
      Tracing: Active
      Events:
        HttpPost: 
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: '/orders'
            Method: post        
      Environment:
        Variables:
          AWS_S3_Bucket: !FindInMap 
            - EnvironmentVariablesMap
            - Function.Properties.Orders.Bucket
            - !Ref EnvironmentType
          DB_SECRET: !FindInMap 
            - EnvironmentVariablesMap
            - DbSecretName
            - !Ref EnvironmentType
          EMAIL_SEND: "andreparis.comp@gmail.com"
          EMAIL_TO: "andreparis.comp@gmail.com"
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupId
        SubnetIds:
          - !Ref SubNetId1
          - !Ref SubNetId2
          - !Ref SubNetId3
          - !Ref SubNetId4
          - !Ref SubNetId5
          - !Ref SubNetId6

